### ISSUE TITLE
MigPlan doesn't notice after "Namespaces not found on ... cluster" is resolved 

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#104]
This message doesn't go away after the namespace in question is created.

```
status:
  conditions:
  - category: Critical
    lastTransitionTime: 2019-05-22T18:34:11Z
    message: Namespaces [nginx-example] not found on the source cluster.
    reason: NotFound
    status: "True"
    type: NamespaceNotFoundOnSourceCluster
```
