### ISSUE TITLE
Need additional fields during PV discovery

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-controller#134]
Currently the reported pv objects look like this when written back to the MigPlan:

```
  persistentVolumes:
  - name: pv1
    supportedActions:
    - copy
    - move
```

The UI requires a number of additional fields for us to render the PV tables as shown in the mocks, the following fields are missing:

`namespace` - the namespace the PV was found in
`size` - size of PV
`claim` - associated pvc name
`storageClass` - associated storageClass, although we'll probably need to think about this more in depth given the issues that Dylan raised around differing storage classes in two different clusters.

**Comment by eriknelson** [comment]
I'm going to close this. I think we'll need some additional fields reported from the controller, but Dylan pointed out that it really doesn't make sense to assign a namespace/claim to a PV, since PVs of course can be in use by more than one claim+namespace. We need to do some additional thinking about the UX on the UI side here.

**Comment by eriknelson** [comment]
Reopening this after discussions with @jwmatthews @djwhatle and @dymurray. We had the incorrect assumption that you could have many PVCs (in different namespaces, potentially) associated with a single PV (cluster-scoped). However, in actuality PVCs have a **one-to-one** relationship with a PV, and multiple pods may use that claim. So, we actually can determine a single namespace and PVC that is associated with a PV. This is data that would be desired in the UI, so we just need to add this info to the PV struct that's written to the spec. Additionally, we determined the size of the PV would be appropriate to add as well, rather than the PVC's claim size, since that's the actual volume getting copy or moved over. In the future, we can get more clever about reporting usage and other metrics.

We'll also need the storageClasses, if any are associated, but that's something we're going to be focusing on for next sprint.

**Comment by eriknelson** [comment]
This sprint we're blocked on knowing the discovered PV storageclass to implement the feature that allows users to choose their destination storage class, see related UI issue linked.

**Comment by jortel** [comment]
The PVs listed on the plan already includes the `StorageClass`.  Is this sufficient?
When asking for the PV `Size`, did you mean the `Capacity`?

Here is an example of what I have so far which adds PVC information.  It also includes both _size_ and _capacity_ for discussion.

```
Persistent Volumes:
    Capacity:
      Storage:  3Gi
    Name:       nfs
    Pvc:
      Name:         nfs
      Namespace:    myproject
    Size:           168
    Storage Class:  NFS
    Supported Actions:
      copy
      move
```

**Comment by jortel** [comment]
Okay, after discussion delivering this:
```
persistentVolumes:
  - capacity: 3Gi
    name: nfs
    pvc:
      name: nfs
      namespace: myproject
    size: 168
    storageClass: NFS
    supportedActions:
    - copy
    - move
```

**Comment by djwhatle** [comment]
> Okay, after discussion delivering this:
> 
> ```
> persistentVolumes:
>   - capacity: 3Gi
>     name: nfs
>     pvc:
>       name: nfs
>       namespace: myproject
>     size: 168
>     storageClass: NFS
>     supportedActions:
>     - copy
>     - move
> ```

FYI @eriknelson, we had to drop size from the list since it isn't accessible from the kube API as far as we've currently seen. By mistake grabbed some bogus data with a promising variable name for that slot before, fixed now.

Will look like this (size left out):
```
persistentVolumes:
  - capacity: 3Gi
    name: nfs
    pvc:
      name: nfs
      namespace: myproject
    storageClass: NFS
    supportedActions:
    - copy
    - move
```
