### ISSUE TITLE
Stage migration is not allowed after failing final migration

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#258]
I noticed that if you attempt a final migration which fails, then go back and attempt a stage migration, the stage migration will never run due to this status condition:

```
  status:
    conditions:
    - category: Critical
      lastTransitionTime: 2019-08-13T19:24:29Z
      message: The associated MigPlan already has a final migration.
      status: "True"
      type: HasFinalMigration
```

I'm not sure this is desired behavior.
